name: "Nix"
on:
  pull_request:
    branches:
      - main
    paths:
      - "flake.nix"
      - "flake.lock"

jobs:
  check_flake:
    name: "Check Flake"
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19

      - run: nix flake check --all-systems
